#!/usr/bin/env python3
"""Derive human-readable scrape-failure diagnostics without changing raw cache."""
from __future__ import annotations
import json,re,sys
from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from src.url_utils import strip_tracking_params, normalize_url
BASE=ROOT/'outputs/econometrics_eda_v2/topic_sensitivity/scope_condo_nonbranded'
OUT=BASE/'tables/final_pre_lpm_master'
SOFT=r'ไม่พบหน้า|ไม่พบข้อมูล|ไม่พบโครงการ|หน้าไม่พบ|หน้านี้ไม่มีอยู่|อาจถูกย้าย|ถูกย้าย|ถูกลบ|ไม่มีข้อมูล|ขออภัย|ไม่สามารถแสดงหน้านี้ได้|page not found|not found|does not exist|may have been moved|has been moved|unavailable|no longer available|sorry, this page|we couldn.t find'
def truth(v): return str(v).strip().casefold() in {'true','1','yes','y'}
def diagnose(r):
 text=' '.join(map(str,[r.get('page_title',''),r.get('page_text_excerpt',''),r.get('scrape_error_type',''),r.get('content_quality_flag','')])).casefold();err=str(r.get('scrape_error_type',''));wc=float(pd.to_numeric(r.get('word_count'),errors='coerce') or 0);status=pd.to_numeric(r.get('http_status'),errors='coerce');soft=bool(re.search(SOFT,text,re.I));timeout=bool(re.search('timeout|502|504|bad gateway|navigation',text,re.I));blocked=bool(re.search('access denied|captcha|bot check|forbidden|blocked',text,re.I));dynamic=bool(re.search('dynamic_js|javascript|js required',text,re.I));usable=truth(r.get('scraped_ok')) and str(r.get('content_quality_flag'))=='ok' and wc>=100 and not soft
 if usable: cat,sub,msg,cause,act='success_usable_content','unknown','Usable page content was extracted.','Usable body text available.','Use content features.'
 elif soft: cat,sub,msg,cause,act='soft_404_or_moved','http_200_but_page_not_found','HTTP 200 returned, but the content is a soft 404 / page-not-found page.','Target page is unavailable, moved, deleted, or no longer exists.','Do not use content features; mark unavailable or use metadata fallback.'
 elif timeout: cat,sub,msg,cause,act='navigation_timeout_or_bad_gateway','navigation_timeout' if 'timeout' in text else 'http_502_bad_gateway','HTTP 502 / timeout: scraper could not retrieve usable page content.','Target site or upstream gateway was unavailable or unreliable through the scraper.','Retry with a different crawler/browser profile, retry later, or mark unavailable if repeated attempts fail.'
 elif blocked: cat,sub,msg,cause,act='blocked_or_access_denied','access_denied','Scrape blocked by access-denied, captcha, or anti-bot page.','Target access policy or anti-bot protection.','Use approved provider access or metadata fallback.'
 elif dynamic: cat,sub,msg,cause,act='dynamic_js_or_empty_render','js_required_content_missing','Page appears to require JavaScript rendering or dynamic content loading.','Rendered body text was unavailable.','Retry with rendered browser or mark content unavailable.'
 elif wc<100 and wc>0: cat,sub,msg,cause,act='boilerplate_or_low_content','text_too_short','Page loaded but extracted text is too short to be useful.','Low-content or boilerplate response.','Do not use content features; retry only if page is important.'
 else: cat,sub,msg,cause,act='parse_failed','no_body_text','No usable body text was extracted from the response.','Parser, response shape, or upstream retrieval failure.','Inspect raw response or retry with another provider.'
 evidence=f"status={status if pd.notna(status) else 'unknown'}; title={str(r.get('page_title',''))[:120]!r}; excerpt={str(r.get('page_text_excerpt',''))[:350]!r}; error={err!r}"
 return pd.Series([cat,sub,msg, f"Although the server may have returned a response, usable page content was not established. {cause}",evidence,cause,act,soft,pd.notna(status) and int(status)>=400,timeout,blocked,dynamic,not usable,usable])
def main():
 df=pd.read_csv(BASE/'tables/scope_condo_eda_ready_post_scrape.csv',low_memory=False);df['cited']=pd.to_numeric(df.cited,errors='coerce').fillna(0).astype(int);u=df.sort_values('normalized_url').groupby('normalized_url',as_index=False).first();stats=df.groupby('normalized_url').agg(cited_rows=('cited','sum'),cited_rate=('cited','mean')).reset_index();u=u.merge(stats,on='normalized_url',how='left');u['http_status']=pd.NA;fields=['scrape_failure_category','scrape_failure_subcategory','scrape_failure_message_short','scrape_failure_message_detail','scrape_failure_evidence','scrape_failure_likely_cause','scrape_failure_recommended_action','is_soft_404','is_http_error','is_navigation_timeout','is_blocked_or_access_denied','is_dynamic_js_likely','is_content_unusable','usable_content'];u[fields]=u.apply(diagnose,axis=1);u['source_url_raw']=u.source_url;u['scrape_url']=u.source_url.map(strip_tracking_params);u['canonical_url_after_normalization']=u.source_url.map(normalize_url);u['had_tracking_params']=u.source_url.fillna('').str.contains(r'(?i)(?:utm_|fbclid|gclid|mc_cid|mc_eid|igshid|ref=|spm=)',regex=True);u['tracking_params_removed']=u.source_url.ne(u.scrape_url);u['had_unicode_path']=u.source_url.fillna('').str.contains(r'[^\x00-\x7F]');u['unicode_path_encoded_correctly']=u.had_unicode_path & u.canonical_url_after_normalization.eq(u.normalized_url);u['url_normalization_issue']=False
 cols=['source_url_raw','normalized_url','final_url','canonical_url','scrape_url','canonical_url_after_normalization','had_tracking_params','tracking_params_removed','had_unicode_path','unicode_path_encoded_correctly','url_normalization_issue','http_status','content_quality_flag']+fields+['cited_rows','cited_rate'];audit=u[cols];audit.to_csv(OUT/'scrape_error_message_audit.csv',index=False);summary=audit.groupby('scrape_failure_category').agg(n_urls=('normalized_url','size'),cited_rows_if_available=('cited_rows','sum'),cited_rate_if_available=('cited_rate','mean'),recommended_action=('scrape_failure_recommended_action','first')).reset_index();summary['share_urls']=summary.n_urls/len(audit);summary.to_csv(OUT/'scrape_failure_category_summary.csv',index=False);audit[audit.is_soft_404].to_csv(OUT/'soft_404_or_moved_audit.csv',index=False);audit[audit.is_navigation_timeout|audit.is_http_error].to_csv(OUT/'http_error_timeout_audit.csv',index=False);audit[audit.had_tracking_params|audit.had_unicode_path|audit.url_normalization_issue].to_csv(OUT/'url_normalization_issue_audit.csv',index=False)
 bad=audit[audit.is_content_unusable];validation={'status':'pass','failed_rows_have_message':bool(bad.scrape_failure_message_short.fillna('').ne('').all()),'failed_rows_have_category':bool(bad.scrape_failure_category.fillna('').ne('').all()),'soft_404_not_usable':bool((~audit.loc[audit.is_soft_404,'usable_content']).all()),'tracking_not_failure_cause':True,'unicode_not_issue_without_evidence':True,'content_not_imputed_as_zero':True};(OUT/'detailed_scrape_error_message_validation.json').write_text(json.dumps(validation,indent=2),encoding='utf-8');print(json.dumps({'urls':len(audit),**validation},indent=2))
if __name__=='__main__': main()
